### PR TITLE
Removes ioredis as dependency from typings

### PR DESCRIPTION
**Pull request by fox1t**
Fixes issue on importing library in TS project and not installing `@types/ioredis`.

### CODE REVIEW

**Comment by fox1t** [comment]
Fixes https://github.com/fastify/fastify-rate-limit/issues/37

**Comment by Eomm** [comment]
@fox1t could we use the [`/// <reference types="..." />`](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html) adding a disclaimer in readme: 

> you may need to install `@types/ioredis`

I'm learning some `typings`, so I'm not 100% sure

**Comment by Eomm** [comment]
> force user installing ioredis types since redis is optional in this case

I agree with this point: I proposed it since it is the same pattern used in fastify for the @type/node dependence but I didn't know all the sides effect, I thought that was necessary only if the property was used in the source code.

So `any` will be ok ✌

**Comment by fox1t** [comment]
Good point on @types/node, but TS on Node.js is unusable without them.  For example,  you can’t even use process.env since process is not defined without them. I consider it a sweet exception, including it as dependency doesn’t hurt the end user.

**Pull request merged**
