### PR TITLE
tests: head routes get applied rate limiting hook only once

### PR DESCRIPTION
**Pull request by Uzlopak**
There was a bug in fastify core, where an onRoute hook would be called twice on automatic generated HEAD routes. This was fixed in core. This PR fixes unit tests and adds one regarding the expected behaviour.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Eomm** [comment]
Can this pr go further now?

**Comment by Uzlopak** [comment]
@Eomm 
No. This PR is actually just about adding a unit test and patch a unit test. Once fastify 4.6.1 is released we can and must apply this PR.
But as long 4.6.0 of fastify is highest version this PR has to wait.

**Review by jsumners — APPROVED** [review]
Looks good to me.

**Comment by Uzlopak** [comment]
thanks

**Pull request merged**
