### PR TITLE
Added grouping routes for ratelimit

### PR DESCRIPTION
**Pull request by aniketcodes**
This PR adds the capability to group various routes and have a common rate limit for them.
#369

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
CI is failing

**Comment by aniket-agi** [comment]
Yeah... There is some issue with the coverage...
I will update the test cases by today.

**Comment by aniketcodes** [comment]
Updated the testcases

**Review by gurgunday — COMMENTED** [review]
it's still red

**Comment by aniketcodes** [comment]
Screenshot 2024-09-04 at 22 41 06

**Comment by aniketcodes** [comment]
It is fixed. @gurgunday

**Comment by aniketcodes** [comment]
Hi @gurgunday / @mcollina Can you please help me with these? Am I missing something with the test?

**Comment by aniketcodes** [comment]
@gurgunday can you please run the CI again?

**Comment by gurgunday** [comment]
I’ll take a look if it’s passing on your end

**Comment by aniketcodes** [comment]
Hi @gurgunday 
Can you please run the CI again?

There was some issue with node_modules and c8. I have fixed them.

**Review by gurgunday — COMMENTED** [review]
Alright, the implementation LGTM, but I'm not really sure why we need it

Why not just group these routes together and extract them into a plugin? rate-limit supports encapsulation, so why not sth like:

```js
fastify.register(async (fastify) => {
  await fastify.register(import("@fastify/rate-limit"), {
    max: 3,
    timeWindow: "1 minute",
  });

  fastify.get(
    "/otp/send",
    (request, reply) => {
      reply.send({ hello: "from ... grouped rate limit" });
    },
  );

  fastify.get(
    "/otp/resend",
    (request, reply) => {
      reply.send({ hello: "from ... grouped rate limit" });
    },
  );
});
```

**Comment by aniketcodes** [comment]
Added it so that it is easily configurable across different route files.

**Comment by aniketcodes** [comment]
@gurgunday Will this implementation enhance the feature of grouping the routes without encapsulation?

**Comment by gurgunday** [comment]
I'm not sure, I feel like we're duplicating functionality and all these small additions might add up to slow down the rate limiter performance

@climba03003 @Uzlopak what do you think? Keep in mind https://github.com/fastify/fastify-rate-limit/pull/380#pullrequestreview-2281036104 already exists

**Comment by gugu** [comment]
> I'm not sure, I feel like we're duplicating functionality and all these small additions might add up to slow down the rate limiter performance

We have a kind-of-common use case for it: we have several similar endpoints. Some of them should be used from frontend, some from backend and so on. If we use per-route rate limit some clever users start to use all similar endpoints to achieve their task and 50 rps becomes 300 rps

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
