### PR TITLE
add route level whitelist

### PR DESCRIPTION
**Pull request by donghc**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by jsumners — COMMENTED** [review]
This will need test coverage.

**Comment by Eomm** [comment]
We should rename the option too

AllowedRoutes would be better 👍🏼

**Comment by jsumners** [comment]
> We should rename the option too

That's a breaking change.

**Comment by Eomm** [comment]
Oh! I forgot about this option.

We can open an issue to deal with it 👍🏼

**Pull request closed without merging**
