### PR TITLE
Typescript types fix for http2/https

### PR DESCRIPTION
**Pull request by ReTWi**
Typescript types fix for http2/https for servers like this:

```
const https: fastify.FastifyInstance<Http2SecureServer, Http2ServerRequest, Http2ServerResponse> = fastify({
  logger: log,
  ignoreTrailingSlash: true,
  http2: true,
  https: { allowHTTP1: true }
})
```

#### Checklist

- [v ] run `npm run test` and `npm run benchmark`
- [v ] tests and/or benchmarks are included
- [- ] documentation is changed or added
- [ v] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Eomm** [comment]
Sorry @ReTWi , could you merge master?

**Comment by ReTWi** [comment]
Merged, but nor sure what is the error :/ @Eomm

**Comment by ReTWi** [comment]
@Eomm 

Ok, today i've run test on my PC without making any changes and after second attempt it passed :/ And then it's passed here. I don't think it's somehow releted to typescript types that was changed is this PR, so we can merge.

As about test fail, here is the description of it, if someone will want to dig into it later on:

```
test/global-rate-limit.test.js .................... 197/197
test/route-rate-limit.test.js ..................... 253/254
  limit reset per Local storage
  not ok should be equal
    --- wanted
    +++ found
    -0
    +-1
    compare: ===
    at:
      line: 686
      column: 9
      file: test/route-rate-limit.test.js
    stack: |
      test/route-rate-limit.test.js:686:9
      node_modules/light-my-request/lib/response.js:26:28
    source: |
      t.strictEqual(res.headers['x-ratelimit-reset'], resetValue)

total ............................................. 450/451


  450 passing (21s)
  1 failing
```

**Comment by Eomm** [comment]
It was flaky CI 👍

**Pull request merged**
