### PR TITLE
fix issue #71 on LocalStore by adding Hook's done callback

### PR DESCRIPTION
**Pull request by samaysar**
Please review, related to (#71). Please add for the next release package. Many thanks.

### CODE REVIEW

**Comment by mcollina** [comment]
Would you mind to add a unit test, so we do not regress?

**Comment by samaysar** [comment]
Ok. I will prepare another PR.

**Comment by Eomm** [comment]
You may update this one 👍

**Comment by samaysar** [comment]
Sorry didn't get time yesterday. Will do.
Btw, would you prefer the full callback as per fastify's hooks document?
Which is addHook('... ', (instance, done) =>{... })???
I see it is using avvio's version with single param... If we stick to
avvio, we can remove 'done' param altogether...

What do you think?

Thanks,

**Comment by Eomm** [comment]
You are right, I think the complete version with `(instance, done)` is better 👍

**Comment by samaysar** [comment]
Thanks for feedback. Let me adjust in the pr.

**Comment by samaysar** [comment]
Hi @Eomm / @mcollina , for your review.

**Pull request merged**
