### PR TITLE
Updated to Fastify v4

### PR DESCRIPTION
**Pull request by mcollina**
Signed-off-by: Matteo Collina <hello@matteocollina.com>

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by DRoet** [comment]
Shouldn't this include the index.js version/name changes?
```js
module.exports = fp(rateLimitPlugin, {
  fastify: '4.x',
  name: '@fastify/rate-limit'
})
```

**Comment by mcollina** [comment]
Good spot, thanks @DRoet!

**Review by climba03003 — CHANGES_REQUESTED** [review]
Missing update of `package.json`

**Review by climba03003 — APPROVED** [review]

**Comment by Eomm** [comment]
fixing it 👍🏽

**Review by climba03003 — APPROVED** [review]
LGTM.

**Pull request merged**
