### PR TITLE
Don't set the reply code automatically

### LINKED ISSUE #284: Don't set the reply code automatically
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

A proposal to modify the behavior of rate limit errors.

Since v4, `fastify-sensible` no longer has the error handler that sets the reply code automatically; `fastify-multipart` doesn't set it either when the Content Too Large error is thrown for instance — they only set the `error.statusCode`, throw, and let the dev decide what to do with that information. 

Currently, `rate-limit` sets the reply code as well as the error code and it breaks things like `reply.redirect("/")` calls in the error handler that don't specify a redirect code.

It's not a huge issue, but a minor inconsistency between plugins IMO.

What do you think?

### Motivation

_No response_

### Example

_No response_

### PR DESCRIPTION
**Pull request by gurgunday**
Closes #284

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] documentation is changed or added

### CODE REVIEW

**Comment by gurgunday** [comment]
I don't get the errors because they were failing before I even made any changes.

As far as I can tell, the changes I made caused no new failures. I also added a new one that would fail before this change.

**Comment by gurgunday** [comment]
Ok, I had done something not smart, reverted that now. Should be good to go.

**Review by mcollina — APPROVED** [review]
lgtm

this is a semver-majorn change

**Comment by bcomnes** [comment]
I have sensible and rate limit both set. Do I need to change anything to update to to v8?

**Comment by gurgunday** [comment]
> I have sensible and rate limit both set. Do I need to change anything to update to to v8?

I have a similar setup and upgrading to v8 required no changes. If you have routes with a custom error handler where you don't set a reply code or use something like `reply.redirect()`, you might need to set the reply code yourself. For other routes, the error response should be identical to v7.

**Comment by bcomnes** [comment]
I see, thank you!

**Pull request merged**
