### PR TITLE
Added the onBanReach Function

### PR DESCRIPTION
**Pull request by DiogoMarques2003**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by DiogoMarques2003** [comment]
Can anyone check why the tests don't pass ?
In my pc is working ...

image

**Comment by Eomm** [comment]
You can check it here: https://github.com/fastify/fastify-rate-limit/runs/7425780475?check_suite_focus=true


spoiler: run `npm run lint:fix` and it should fix the issue

**Comment by DiogoMarques2003** [comment]
@DiogoMarques2003 done

**Comment by DiogoMarques2003** [comment]
@Eomm done

**Review by Eomm — APPROVED** [review]

**Review by RafaelGSS — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
