### PR TITLE
Update errorResponseBuilderContext type with ban property

### PR DESCRIPTION
**Pull request by leonitousconforti**
According to the README: `When the ban limit is exceeded the context field will have ban=true in the errorResponseBuilder.` This just updates the types to reflect that. I have been using the field and it works as expected, just updating the types so I don't have to use a ts-ignore comment

#### Checklist

- [ ] ~run `npm run test` and `npm run benchmark`~ not needed?
- [X] tests and/or benchmarks are included
- [ ] ~documentation is changed or added~ documentation is already correct
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by leonitousconforti** [comment]
Not entirely sure why all those tests are failing, but I don't understand how it could be from my change to the types

**Comment by Eomm** [comment]
It is due to this PR: https://github.com/fastify/light-my-request/pull/248

We need to update the comparisons

**Comment by Uzlopak** [comment]
@Eomm 
created a PR to fix the CI

**Comment by Eomm** [comment]
can't update the branch tho

**Comment by Eomm** [comment]
@leonitousconforti could you add a test here https://github.com/fastify/fastify-rate-limit/blob/master/types/index.test-d.ts too?

**Comment by leonitousconforti** [comment]
Let me know what you think about the changes to the tests

**Review by Eomm — APPROVED** [review]

**Pull request merged**
