### PR TITLE
Implemented addHeadersOnExceeding

### PR DESCRIPTION
**Pull request by TheTimmaeh**
Added a new param addHeadersOnExceeding for advanced control over which headers are shown before the limit is reached, as discussed in https://github.com/fastify/fastify-rate-limit/issues/166.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by zekth — CHANGES_REQUESTED** [review]
Can you add types for this option also?

**Comment by TheTimmaeh** [comment]
I'm not fluent in TS, I assume this is what you're looking for?

**Review by mcollina — APPROVED** [review]
lgtm

**Review by zekth — APPROVED** [review]
lgtm. Thanks

**Pull request merged**
