### PR TITLE
add the "key" in the "onExceeding" and "onBanReach"

### PR DESCRIPTION
**Pull request by SergioGlorias**
#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [X] tests and/or benchmarks are included
- [X] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
why the key? why not the actual IP?

**Comment by SergioGlorias** [comment]
> why the key? why not the actual IP?

i'm working on some things that can't directly be the IP the default key
and there are people who use keys different from the default IP

`onBanReach` already provides the key is a big help
only these two functions do not have the key

**Review by Uzlopak — APPROVED** [review]
LGTM

**Review by mcollina — APPROVED** [review]
lgtm

**Review by mcollina — CHANGES_REQUESTED** [review]
Thanks for opening a PR! Can you please add a unit test?

**Comment by SergioGlorias** [comment]
@mcollina I don't have much practice with this but could you check?

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
